In [1]:
import numpy as np
import pandas as pd
import scipy
from scipy import stats
import suncalc

import dask.dataframe as dd
from pathlib import Path
from tqdm import tqdm
import re

import datetime as dt

import matplotlib.pyplot as plt
from matplotlib import colors
import soundfile as sf
import matplotlib.patches as patches

In [2]:
import sys

sys.path.append("../src")
sys.path.append("../src/activity")

In [3]:
import subsampling as ss
import activity_assembly as actvt
import bout.assembly as bt
import comparison.data_assembly as comp
import comparison.plot as complot
from core import SITE_NAMES

from cli import get_file_paths
import plot
import pipeline

In [23]:
site_key = 'Telephone'
type_key = ''

data_params = dict()
data_params["site_tag"] = site_key
data_params["site_name"] = SITE_NAMES[site_key]
data_params["type_tag"] = type_key
data_params['detector_tag'] = 'bd2'
data_params['assembly_type'] = 'kmeans'
data_params['training_set'] = 'all_locations'
file_paths = get_file_paths(data_params)

In [5]:
location_classes = pd.read_csv(file_paths['SITE_classes_file'], index_col=0)
(Path(file_paths['SITE_classes_folder']) / 'file_level').mkdir(parents=True, exist_ok=True)

In [6]:
def save_individual_file_classes(file_classes):
    print(f'{Path(file_classes.name).stem}')
    save_filename = f'{data_params["detector_tag"]}__{data_params["site_tag"]}_{Path(file_classes.name).stem}_classes'
    file_classes.to_csv(Path(file_paths['SITE_classes_folder']) / f'file_level/{save_filename}.csv')

In [31]:
location_classes_grouped_by_file = location_classes.groupby('file_name')

In [32]:
location_classes_grouped_by_file.apply(lambda x: save_individual_file_classes(x))

20220723_000000
20220723_003000
20220723_010000
20220723_013000
20220723_020000
20220723_023000
20220723_030000
20220723_033000
20220723_040000
20220723_043000
20220723_050000
20220723_053000
20220723_060000
20220723_063000
20220723_070000
20220723_073000
20220723_080000
20220723_083000
20220723_090000
20220723_093000
20220723_100000
20220723_103000
20220723_110000
20220723_113000
20220723_120000
20220723_123000
20220723_130000
20220723_133000
20220723_140000
20220723_143000
20220723_150000
20220723_153000
20220724_000000
20220724_003000
20220724_010000
20220724_013000
20220724_020000
20220724_023000
20220724_030000
20220724_033000
20220724_040000
20220724_043000
20220724_050000
20220724_053000
20220724_060000
20220724_063000
20220724_070000
20220724_073000
20220724_080000
20220724_083000
20220724_090000
20220724_093000
20220724_100000
20220724_103000
20220724_110000
20220724_113000
20220724_120000
20220724_123000
20220724_130000
20220724_133000
20220724_140000
20220724_143000
20220724_150000
20220724_153000
20220725_000000
20220725_003000
20220725_010000
20220725_013000
20220725_020000
20220725_023000
20220725_030000
20220725_033000
20220725_040000
20220725_043000
20220725_050000
20220725_053000
20220725_060000
20220725_063000
20220725_070000
20220725_073000
20220725_080000
20220725_083000
20220725_090000
20220725_093000
20220725_100000
20220725_103000
20220725_110000
20220725_113000
20220725_120000
20220725_123000
20220725_130000
20220725_133000
20220725_140000
20220725_143000
20220725_150000
20220725_153000
20220819_010000
20220819_013000
20220819_020000
20220819_023000
20220819_030000
20220819_033000
20220819_040000
20220819_043000
20220819_050000
20220819_053000
20220819_060000
20220819_063000
20220819_070000
20220819_073000
20220819_080000
20220819_083000
20220819_090000
20220819_093000
20220819_100000
20220819_103000
20220819_110000
20220819_113000
20220819_120000
20220819_123000
20220819_130000
20220819_133000
20220819_140000
20220819_143000
20220819_150000
20220819_153000
20220820_000000
20220820_003000
20220820_010000
20220820_013000
20220820_020000
20220820_023000
20220820_030000
20220820_033000
20220820_040000
20220820_043000
20220820_050000
20220820_053000
20220820_060000
20220820_063000
20220820_070000
20220820_073000
20220820_080000
20220820_083000
20220820_090000
20220820_093000
20220820_100000
20220820_103000
20220820_110000
20220820_113000
20220820_120000
20220820_123000
20220820_130000
20220820_133000
20220820_140000
20220820_143000
20220820_150000
20220820_153000
20220821_000000
20220821_003000
20220821_010000
20220821_013000
20220821_020000
20220821_023000
20220821_030000
20220821_033000
20220821_040000
20220821_043000
20220821_050000
20220821_053000
20220821_060000
20220821_063000
20220821_070000
20220821_073000
20220821_080000
20220821_083000
20220821_090000
20220821_093000
20220821_100000
20220821_103000
20220821_110000
20220821_113000
20220821_120000
20220821_123000
20220821_130000
20220821_133000
20220821_140000
20220821_143000
20220821_150000
20220821_153000
20220822_000000
20220822_003000
20220822_010000
20220822_013000
20220822_020000
20220822_023000
20220822_030000
20220822_033000
20220822_040000
20220822_043000
20220822_050000
20220822_053000
20220822_060000
20220822_063000
20220822_070000
20220822_073000
20220822_080000
20220822_083000
20220822_090000
20220822_093000
20220822_100000
20220822_103000
20220822_110000
20220822_113000
20220822_120000
20220822_123000
20220822_130000
20220822_133000
20220822_140000
20220822_143000
20220822_150000
20220822_153000
20220823_000000
20220823_003000
20220823_010000
20220823_013000
20220823_020000
20220823_023000
20220823_030000
20220823_033000
20220823_040000
20220823_043000
20220823_050000
20220823_053000
20220823_060000
20220823_063000
20220823_070000
20220823_073000
20220823_080000
20220823_083000
20220823_090000
20220823_093000
20220823_100000
20220823_103000
20220823_110000
20220823_113000
20220823_120000
20220823_123000
20220823_130000
20220823_133000
20220823_140000
20220823_143000
20220823_150000
20220823_153000
20220824_000000
20220824_003000
20220824_010000
20220824_013000
20220824_020000
20220824_023000
20220824_030000
20220824_033000
20220824_040000
20220824_043000
20220824_050000
20220824_053000
20220824_060000
20220824_063000
20220824_070000
20220824_073000
20220824_080000
20220824_083000
20220824_090000
20220824_093000
20220824_100000
20220824_103000
20220824_110000
20220824_113000
20220824_120000
20220824_123000
20220824_130000
20220824_133000
20220824_140000
20220824_143000
20220824_150000
20220824_153000
20220825_000000
20220825_003000
20220825_010000
20220825_013000
20220825_020000
20220825_023000
20220825_030000
20220825_033000
20220825_040000
20220825_043000
20220825_050000
20220825_053000
20220825_060000
20220825_063000
20220825_070000
20220825_073000
20220825_080000
20220825_083000
20220825_090000
20220825_093000
20220825_100000
20220825_103000
20220825_110000
20220825_113000
20220825_120000
20220825_123000
20220825_130000
20220825_133000
20220825_140000
20220825_143000
20220825_150000
20220825_153000
20220826_000000
20220826_010000
20220826_013000
20220826_020000
20220826_023000
20220826_030000
20220826_033000
20220826_040000
20220826_043000
20220826_050000
20220826_053000
20220826_060000
20220826_063000
20220826_070000
20220826_073000
20220826_080000
20220826_083000
20220826_090000
20220826_093000
20220826_100000
20220826_103000
20220826_110000
20220826_113000
20220826_120000
20220826_123000
20220826_130000
20220826_133000
20220826_140000
20220826_143000
20220826_150000
20220826_153000
20220827_000000
20220827_003000
20220827_010000
20220827_013000
20220827_020000
20220827_023000
20220827_030000
20220827_033000
20220827_040000
20220827_043000
20220827_050000
20220827_053000
20220827_060000
20220827_063000
20220827_070000
20220827_073000
20220827_080000
20220827_083000
20220827_090000
20220827_093000
20220827_100000
20220827_103000
20220827_110000
20220827_113000
20220827_120000
20220827_123000
20220827_130000
20220827_133000
20220827_140000
20220827_143000
20220827_150000
20220827_153000
20220828_000000
20220828_003000
20220828_010000
20220828_013000
20220828_020000
20220828_023000
20220828_030000
20220828_033000
20220828_040000
20220828_043000
20220828_050000
20220828_053000
20220828_060000
20220828_063000
20220828_070000
20220828_073000
20220828_080000
20220828_083000
20220828_090000
20220828_093000
20220828_100000
20220828_103000
20220828_110000
20220828_113000
20220828_120000
20220828_123000
20220828_130000
20220828_133000
20220828_140000
20220828_143000
20220828_150000
20220828_153000
20220829_000000
20220829_003000
20220829_010000
20220829_013000
20220829_020000
20220829_023000
20220829_030000
20220829_033000
20220829_040000
20220829_043000
20220829_050000
20220829_053000
20220829_060000
20220829_063000
20220829_070000
20220829_073000
20220829_080000
20220829_083000
20220829_090000
20220829_093000
20220829_100000
20220829_103000
20220829_110000
20220829_113000
20220829_120000
20220829_123000
20220829_130000
20220829_133000
20220829_140000
20220829_143000
20220829_150000
20220829_153000
20220830_000000
20220830_003000
20220830_010000
20220830_013000
20220830_020000
20220830_023000
20220830_030000
20220830_033000
20220830_040000
20220830_043000
20220830_050000
20220830_053000
20220830_060000
20220830_063000
20220830_070000
20220830_073000
20220830_080000
20220830_083000
20220830_090000
20220830_093000
20220830_100000
20220830_103000
20220830_110000
20220830_113000
20220830_120000
20220830_123000
20220830_130000
20220830_133000
20220830_140000
20220830_143000
20220830_150000
20220830_153000
20220831_000000
20220831_003000
20220831_010000
20220831_013000
20220831_020000
20220831_023000
20220831_030000
20220831_033000
20220831_040000
20220831_043000
20220831_050000
20220831_053000
20220831_060000
20220831_063000
20220831_070000
20220831_073000
20220831_080000
20220831_083000
20220831_090000
20220831_093000
20220831_100000
20220831_103000
20220831_110000
20220831_113000
20220831_120000
20220831_123000
20220831_130000
20220831_133000
20220831_140000
20220831_143000
20220831_150000
20220831_153000
20220901_000000
20220901_003000
20220901_010000
20220901_013000
20220901_020000
20220901_023000
20220901_030000
20220901_033000
20220901_040000
20220901_043000
20220901_050000
20220901_053000
20220901_060000
20220901_063000
20220901_070000
20220901_073000
20220901_080000
20220901_083000
20220901_090000
20220901_093000
20220901_100000
20220901_103000
20220901_110000
20220901_113000
20220901_120000
20220901_123000
20220901_130000
20220901_133000
20220901_140000
20220901_143000
20220901_150000
20220901_153000
20220902_003000
20220902_010000
20220902_013000
20220902_020000
20220902_023000
20220902_030000
20220902_033000
20220902_040000
20220902_043000
20220902_050000
20220902_053000
20220902_060000
20220902_063000
20220902_070000
20220902_073000
20220902_080000
20220902_083000
20220902_090000
20220902_093000
20220902_100000
20220902_103000
20220902_110000
20220902_113000
20220902_120000
20220902_123000
20220902_130000
20220902_133000
20220902_140000
20220902_143000
20220902_150000
20220902_153000
20220903_000000
20220903_003000
20220903_010000
20220903_013000
20220903_020000
20220903_023000
20220903_030000
20220903_033000
20220903_040000
20220903_043000
20220903_050000
20220903_053000
20220903_060000
20220903_063000
20220903_070000
20220903_073000
20220903_080000
20220903_083000
20220903_090000
20220903_093000
20220903_100000
20220903_103000
20220903_110000
20220903_113000
20220903_120000
20220903_123000
20220903_130000
20220903_133000
20220903_140000
20220903_143000
20220903_150000
20220903_153000
20220904_000000
20220904_003000
20220904_010000
20220904_013000
20220904_020000
20220904_023000
20220904_030000
20220904_033000
20220909_003000
20220909_010000
20220909_013000
20220909_020000
20220909_023000
20220909_030000
20220909_033000
20220909_040000
20220909_043000
20220909_050000
20220909_053000
20220909_060000
20220909_063000
20220909_070000
20220909_073000
20220909_080000
20220909_083000
20220909_090000
20220909_093000
20220909_100000
20220909_103000
20220909_110000
20220909_113000
20220909_120000
20220909_123000
20220909_130000
20220909_133000
20220909_140000
20220909_143000
20220909_150000
20220909_153000
20220910_000000
20220910_003000
20220910_010000
20220910_013000
20220910_020000
20220910_023000
20220910_030000
20220910_033000
20220910_040000
20220910_043000
20220910_050000
20220910_053000
20220910_060000
20220910_063000
20220910_070000
20220910_073000
20220910_080000
20220910_083000
20220910_090000
20220910_093000
20220910_100000
20220910_103000
20220910_110000
20220910_113000
20220910_120000
20220910_123000
20220910_130000
20220910_133000
20220910_140000
20220910_143000
20220910_150000
20220910_153000
20220911_000000
20220911_003000
20220911_010000
20220911_013000
20220911_020000
20220911_023000
20220911_030000
20220911_033000
20220911_040000
20220911_043000
20220911_050000
20220911_053000
20220911_060000
20220911_063000
20220911_070000
20220911_073000
20220911_080000
20220911_083000
20220911_090000
20220911_093000
20220911_100000
20220911_103000
20220911_110000
20220911_113000
20220911_120000
20220911_123000
20220911_130000
20220911_133000
20220911_140000
20220911_143000
20220911_150000
20220911_153000
20220912_000000
20220912_003000
20220912_010000
20220912_013000
20220912_020000
20220912_023000
20220912_030000
20220912_033000
20220912_040000
20220912_043000
20220912_050000
20220912_053000
20220912_060000
20220912_063000
20220912_070000
20220912_073000
20220913_000000
20220913_003000
20220913_010000
20220913_013000
20220913_020000
20220913_023000
20220913_030000
20220913_033000
20220913_040000
20220913_043000
20220913_050000
20220913_053000
20220913_060000
20220913_063000
20220913_070000
20220913_073000
20220913_080000
20220913_083000
20220913_090000
20220913_093000
20220913_100000
20220913_103000
20220913_110000
20220913_113000
20220913_120000
20220913_123000
20220913_130000
20220913_133000
20220913_140000
20220913_143000
20220913_150000
20220913_153000
20220914_000000
20220914_003000
20220914_010000
20220914_013000
20220914_020000
20220914_023000
20220914_030000
20220914_033000
20220914_040000
20220914_043000
20220914_050000
20220914_053000
20220914_060000
20220914_063000
20220914_070000
20220914_073000
20220914_080000
20220914_083000
20220914_090000
20220914_093000
20220914_100000
20220914_103000
20220914_110000
20220914_113000
20220914_120000
20220914_123000
20220914_130000
20220914_133000
20220914_140000
20220914_143000
20220914_150000
20220914_153000
20220915_000000
20220915_003000
20220915_010000
20220915_013000
20220915_020000
20220915_023000
20220915_030000
20220915_033000
20220915_040000
20220915_043000
20220915_050000
20220915_053000
20220915_060000
20220915_063000
20220915_070000
20220915_073000
20220915_080000
20220915_083000
20220915_090000
20220915_093000
20220915_100000
20220915_103000
20220915_110000
20220915_113000
20220915_120000
20220915_123000
20220915_130000
20220915_133000
20220915_140000
20220915_143000
20220915_150000
20220915_153000
20220916_000000
20220916_003000
20220916_010000
20220916_013000
20220916_020000
20220916_023000
20220916_030000
20220916_033000
20220916_040000
20220916_043000
20220916_050000
20220916_053000
20220916_060000
20220916_063000
20220916_070000
20220916_073000
20220916_080000
20220916_083000
20220916_090000
20220916_093000
20220916_100000
20220916_103000
20220916_110000
20220916_113000
20220916_120000
20220916_123000
20220916_130000
20220916_133000
20220916_140000
20220916_143000
20220916_150000
20220916_153000
20220917_000000
20220917_003000
20220917_010000
20220917_013000
20220917_020000
20220917_023000
20220917_030000
20220917_033000
20220917_040000
20220917_043000
20220917_050000
20220917_053000
20220917_060000
20220917_063000
20220917_070000
20220917_073000
20220917_080000
20220917_083000
20220917_090000
20220917_093000
20220917_100000
20220917_103000
20220917_110000
20220917_113000
20220917_120000
20220917_123000
20220917_130000
20220917_133000
20220917_140000
20220917_143000
20220917_150000
20220917_153000
20220918_000000
20220918_003000
20220918_010000
20220918_013000
20220918_020000
20220918_023000
20220918_030000
20220918_033000
20220918_040000
20220918_043000
20220918_050000
20220918_053000
20220918_060000
20220918_063000
20220918_070000
20220918_073000
20220918_080000
20220918_083000
20220918_090000
20220918_093000
20220918_100000
20220918_103000
20220918_110000
20220918_113000
20220918_120000
20220918_123000
20220918_130000
20220918_133000
20220918_140000
20220918_143000
20220918_150000
20220918_153000
20220919_000000
20220919_003000
20220919_010000
20220919_013000
20220919_020000
20220919_023000
20220919_030000
20220919_033000
20220919_040000
20220919_043000
20220919_050000
20220919_053000
20220919_060000
20220919_063000
20220919_070000
20220919_073000
20220919_080000
20220919_083000
20220919_090000
20220919_093000
20220919_100000
20220919_103000
20220919_110000
20220919_113000
20220919_120000
20220919_123000
20220919_130000
20220919_133000
20220919_140000
20220919_143000
20220919_150000
20220919_153000
20220920_003000
20220920_010000
20220920_013000
20220920_020000
20220920_023000
20220920_030000
20220920_033000
20220920_040000
20220920_043000
20220920_050000
20220920_053000
20220920_060000
20220920_063000
20220920_070000
20220920_073000
20220920_080000
20220920_083000
20220920_090000
20220920_093000
20220920_100000
20220920_103000
20220920_110000
20220920_113000
20220920_120000
20220920_123000
20220920_130000
20220920_133000
20220920_140000
20220920_143000
20220920_150000
20220920_153000
20220921_000000
20220921_003000
20220921_010000
20220921_013000
20220921_020000
20220921_023000
20220921_030000
20220921_033000
20220921_040000
20220921_043000
20220921_050000
20220921_053000
20220921_060000
20220921_063000
20220921_070000
20220921_073000
20220921_080000
20220921_083000
20220921_090000
20220921_093000
20220921_100000
20220921_103000
20220921_110000
20220921_113000
20220921_120000
20220921_123000
20220921_130000
20220921_133000
20220921_140000
20220921_143000
20220921_150000
20220921_153000
20220922_000000
20220922_003000
20220922_010000
20220922_013000
20220922_020000
20220922_023000
20220922_030000
20220922_033000
20220922_040000
20220922_043000
20220922_050000
20220922_053000
20220922_060000
20220922_063000
20220922_070000
20220922_073000
20220922_080000
20220922_083000
20220922_090000
20220922_093000
20220922_100000
20220922_103000
20220922_110000
20220922_113000
20220922_120000
20220922_123000
20220922_130000
20220922_133000
20220922_140000
20220922_143000
20220922_150000
20220922_153000
20220923_000000
20220923_003000
20220923_010000
20220923_013000
20220923_020000
20220923_023000
20220923_030000
20220923_033000
20220923_040000
20220923_043000
20220923_050000
20220923_053000
20220923_060000
20220923_063000
20220923_070000
20220923_073000
20220923_080000
20220923_083000
20220923_090000
20220923_093000
20220923_100000
20220923_103000
20220923_110000
20220923_113000
20220923_120000
20220923_123000
20220923_130000
20220923_133000
20220923_140000
20220923_143000
20220923_150000
20220923_153000
20220924_000000
20220924_003000
20220924_010000
20220924_013000
20220924_020000
20220924_023000
20220924_030000
20220924_033000
20220924_040000
20220924_043000
20220924_050000
20220924_053000
20220924_060000
20220924_063000
20220924_070000
20220924_073000
20220924_080000
20220924_083000
20220924_090000
20220924_093000
20220924_100000
20220924_103000
20220924_110000
20220924_113000
20220924_120000
20220924_123000
20220924_130000
20220924_133000
20220924_140000
20220924_143000
20220924_150000
20220924_153000
20220925_000000
20220925_003000
20220925_010000
20220925_013000
20220925_020000
20220925_023000
20220925_030000
20220925_033000
20220925_040000
20220925_043000
20220925_050000
20220925_053000
20220925_060000
20220925_063000
20220925_070000
20220925_073000
20220925_080000
20220925_083000
20220925_090000
20220925_093000
20220925_100000
20220925_103000
20220925_110000
20220925_113000
20220925_120000
20220925_123000
20220925_130000
20220925_133000
20220925_140000
20220925_143000
20220925_150000
20220925_153000
20220926_000000
20220926_003000
20220926_010000
20220926_013000
20220926_020000
20220926_023000
20220926_030000
20220926_033000
20220926_040000
20220926_043000
20220926_050000
20220926_053000
20220926_060000
20220926_063000
20220926_070000
20220926_073000
20220926_080000
20220926_083000
20220926_090000
20220926_093000
20220926_100000
20220926_103000
20220926_110000
20220926_113000
20220926_120000
20220926_123000
20220926_130000
20220926_133000
20220926_140000
20220926_143000
20220926_150000
20220926_153000
20220927_000000
20220927_003000
20220927_010000
20220927_013000
20220927_020000
20220927_023000
20220927_030000
20220927_033000
20220927_040000
20220927_043000
20220927_050000
20220927_053000
20220927_060000
20220927_063000
20220927_070000
20220927_073000
20220927_080000
20220927_083000
20220927_090000
20220927_093000
20220927_100000
20220927_103000
20220927_110000
20220927_113000
20220927_120000
20220927_123000
20220927_130000
20220927_133000
20220927_140000
20220927_143000
20220927_150000
20220927_153000
20220928_000000
20220928_003000
20220928_010000
20220928_013000
20220928_020000
20220928_023000
20220928_030000
20220928_033000
20220928_040000
20220928_043000
20220928_050000
20220928_053000
20220928_060000
20220928_063000
20220928_070000
20220928_073000
20220928_080000
20220928_083000
20220928_090000
20220928_093000
20220928_100000
20220928_103000
20220928_110000
20220928_113000
20220928_120000
20220928_123000
20220928_130000
20220928_133000
20220928_140000
20220928_143000
20220928_150000
20220928_153000
20220929_000000
20220929_003000
20220929_010000
20220929_013000
20220929_020000
20220929_023000
20220929_030000
20220929_033000
20220929_040000
20220929_043000
20220929_050000
20220929_053000
20220929_060000
20220929_063000
20220929_070000
20220929_073000

Empty DataFrame
Columns: []
Index: []

In [48]:
location_df = pd.read_csv(Path(file_paths['SITE_folder']) / f"{file_paths['detector_TYPE_SITE_YEAR']}.csv", index_col=0)
(Path(file_paths['SITE_folder']) / 'file_level').mkdir(parents=True, exist_ok=True)

In [49]:
def save_individual_file_classified_dets(file_dets):
    print(f'{Path(file_dets.name).stem}')
    save_filename = f'{data_params["detector_tag"]}__{data_params["site_tag"]}_{Path(file_dets.name).stem}_classified'
    file_dets.to_csv(Path(file_paths['SITE_folder']) / f'file_level/{save_filename}.csv')

In [50]:
location_classed_dets_grouped_by_file = location_df.groupby('input_file')

In [51]:
location_classed_dets_grouped_by_file.apply(lambda x: save_individual_file_classified_dets(x))

20220713_000000
20220713_003000
20220713_010000
20220713_013000
20220713_020000
20220713_023000
20220713_030000
20220713_033000
20220713_040000
20220713_043000
20220713_050000
20220713_053000
20220713_060000
20220713_063000
20220713_070000
20220713_073000
20220713_080000
20220713_083000
20220713_090000
20220713_093000
20220713_100000
20220713_103000
20220713_110000
20220713_113000
20220713_120000
20220713_123000
20220713_130000
20220713_133000
20220713_140000
20220713_143000
20220713_150000
20220713_153000
20220714_000000
20220714_003000
20220714_010000
20220714_013000
20220714_020000
20220714_023000
20220714_030000
20220714_033000
20220714_040000
20220714_043000
20220714_050000
20220714_053000
20220714_060000
20220714_063000
20220714_070000
20220714_073000
20220714_080000
20220714_083000
20220714_090000
20220714_093000
20220714_100000
20220714_103000
20220714_110000
20220714_113000
20220714_120000
20220714_123000
20220714_130000
20220714_133000
20220714_140000
20220714_143000
20220714_150000
20220714_153000
20220715_000000
20220715_003000
20220715_010000
20220715_013000
20220715_020000
20220715_023000
20220715_030000
20220715_033000
20220715_040000
20220715_043000
20220715_050000
20220715_053000
20220715_060000
20220715_063000
20220715_070000
20220715_073000
20220715_080000
20220715_083000
20220715_090000
20220715_093000
20220715_100000
20220715_103000
20220715_110000
20220715_113000
20220715_120000
20220715_123000
20220716_000000
20220716_003000
20220716_010000
20220716_013000
20220716_020000
20220716_023000
20220716_030000
20220716_033000
20220716_040000
20220716_043000
20220716_050000
20220716_053000
20220716_060000
20220716_063000
20220716_070000
20220716_073000
20220716_080000
20220716_083000
20220716_090000
20220716_093000
20220716_100000
20220716_103000
20220716_110000
20220716_113000
20220716_120000
20220716_123000
20220716_130000
20220716_133000
20220716_140000
20220716_143000
20220716_150000
20220716_153000
20220717_000000
20220717_003000
20220717_010000
20220717_013000
20220717_020000
20220717_023000
20220717_030000
20220717_033000
20220717_040000
20220717_043000
20220717_050000
20220717_053000
20220717_060000
20220717_063000
20220717_070000
20220717_073000
20220717_080000
20220717_083000
20220717_090000
20220717_093000
20220717_100000
20220717_103000
20220717_110000
20220717_113000
20220717_120000
20220717_123000
20220717_130000
20220717_133000
20220717_140000
20220717_143000
20220717_150000
20220717_153000
20220718_000000
20220718_003000
20220718_010000
20220718_013000
20220718_020000
20220718_023000
20220718_030000
20220718_033000
20220718_040000
20220718_043000
20220718_050000
20220718_053000
20220718_060000
20220718_063000
20220718_070000
20220718_073000
20220718_080000
20220718_083000
20220718_090000
20220718_093000
20220718_100000
20220718_103000
20220718_110000
20220718_113000
20220718_120000
20220718_123000
20220718_130000
20220718_133000
20220718_140000
20220718_143000
20220718_150000
20220718_153000
20220719_000000
20220719_003000
20220719_010000
20220719_013000
20220719_020000
20220719_023000
20220719_030000
20220719_033000
20220719_040000
20220719_043000
20220719_050000
20220719_053000
20220719_060000
20220719_063000
20220719_070000
20220719_073000
20220719_080000
20220719_083000
20220719_090000
20220719_093000
20220719_100000
20220719_103000
20220719_110000
20220719_113000
20220719_120000
20220719_123000
20220719_130000
20220719_133000
20220719_140000
20220719_143000
20220719_150000
20220719_153000
20220720_000000
20220720_003000
20220720_010000
20220720_013000
20220720_020000
20220720_023000
20220720_030000
20220720_033000
20220720_040000
20220720_043000
20220720_050000
20220720_053000
20220720_060000
20220720_063000
20220720_070000
20220720_073000
20220720_080000
20220720_083000
20220720_090000
20220720_093000
20220720_100000
20220720_103000
20220720_110000
20220720_113000
20220720_120000
20220720_123000
20220720_130000
20220720_133000
20220720_140000
20220720_143000
20220720_150000
20220720_153000
20220721_000000
20220721_003000
20220721_010000
20220721_013000
20220721_020000
20220721_023000
20220721_030000
20220721_033000
20220721_040000
20220721_043000
20220721_050000
20220721_053000
20220721_060000
20220721_063000
20220721_070000
20220721_073000
20220721_080000
20220721_083000
20220721_090000
20220721_093000
20220721_100000
20220721_103000
20220721_110000
20220721_113000
20220721_120000
20220721_123000
20220721_130000
20220721_133000
20220721_140000
20220721_143000
20220721_150000
20220721_153000
20220722_000000
20220722_003000
20220722_010000
20220722_013000
20220722_020000
20220722_023000
20220722_030000
20220722_033000
20220722_040000
20220722_043000
20220722_050000
20220722_053000
20220722_060000
20220722_063000
20220722_070000
20220722_073000
20220722_080000
20220722_083000
20220722_090000
20220722_093000
20220722_100000
20220722_103000
20220722_110000
20220722_113000
20220722_120000
20220722_123000
20220722_130000
20220722_133000
20220722_140000
20220722_143000
20220722_150000
20220722_153000
20220723_000000
20220723_003000
20220723_010000
20220723_013000
20220723_020000
20220723_023000
20220723_030000
20220723_033000
20220723_040000
20220723_043000
20220723_050000
20220723_053000
20220723_060000
20220723_063000
20220723_070000
20220723_073000
20220723_080000
20220723_083000
20220723_090000
20220723_093000
20220723_100000
20220723_103000
20220723_110000
20220723_113000
20220723_120000
20220723_123000
20220723_130000
20220723_133000
20220723_140000
20220723_143000
20220723_150000
20220723_153000
20220724_000000
20220724_003000
20220724_010000
20220724_013000
20220724_020000
20220724_023000
20220724_030000
20220724_033000
20220724_040000
20220724_043000
20220724_050000
20220724_053000
20220724_060000
20220724_063000
20220724_070000
20220724_073000
20220724_080000
20220724_083000
20220724_090000
20220724_093000
20220724_100000
20220724_103000
20220724_110000
20220724_113000
20220724_120000
20220724_123000
20220724_130000
20220724_133000
20220724_140000
20220724_143000
20220724_150000
20220724_153000
20220725_000000
20220725_003000
20220725_010000
20220725_013000
20220725_020000
20220725_023000
20220725_030000
20220725_033000
20220725_040000
20220725_043000
20220725_050000
20220725_053000
20220725_060000
20220725_063000
20220725_070000
20220725_073000
20220725_080000
20220725_083000
20220725_090000
20220725_093000
20220725_100000
20220725_103000
20220725_110000
20220725_113000
20220725_120000
20220725_123000
20220725_130000
20220725_133000
20220725_140000
20220725_143000
20220725_150000
20220725_153000
20220726_000000
20220726_003000
20220726_010000
20220726_013000
20220726_020000
20220726_023000
20220726_030000
20220726_033000
20220726_040000
20220726_043000
20220726_050000
20220726_053000
20220726_060000
20220726_063000
20220726_070000
20220726_073000
20220726_080000
20220726_083000
20220726_090000
20220726_093000
20220726_100000
20220726_103000
20220726_110000
20220726_113000
20220726_120000
20220726_123000
20220726_130000
20220726_133000
20220726_140000
20220726_143000
20220726_150000
20220726_153000
20220727_000000
20220727_003000
20220727_010000
20220727_013000
20220727_020000
20220727_023000
20220727_030000
20220727_033000
20220727_040000
20220727_043000
20220727_050000
20220727_053000
20220727_060000
20220727_063000
20220727_070000
20220727_073000
20220727_080000
20220727_083000
20220727_090000
20220727_093000
20220727_100000
20220727_103000
20220727_110000
20220727_113000
20220727_120000
20220727_123000
20220727_130000
20220727_133000
20220727_140000
20220727_143000
20220727_150000
20220727_153000
20220728_000000
20220728_003000
20220728_010000
20220728_013000
20220728_020000
20220728_023000
20220728_030000
20220728_033000
20220728_040000
20220728_043000
20220728_050000
20220728_053000
20220728_060000
20220728_063000
20220728_070000
20220728_073000
20220728_080000
20220728_083000
20220728_090000
20220728_093000
20220728_100000
20220728_103000
20220728_110000
20220728_113000
20220728_120000
20220728_123000
20220728_130000
20220728_133000
20220728_140000
20220728_143000
20220728_150000
20220728_153000
20220729_020000
20220729_023000
20220729_030000
20220729_033000
20220729_040000
20220729_043000
20220729_050000
20220729_053000
20220729_060000
20220729_063000
20220729_070000
20220729_073000
20220729_080000
20220729_083000
20220729_090000
20220729_093000
20220729_100000
20220729_103000
20220729_110000
20220729_113000
20220729_120000
20220729_123000
20220729_130000
20220729_133000
20220729_140000
20220729_143000
20220729_150000
20220729_153000
20220730_000000
20220730_003000
20220730_010000
20220730_013000
20220730_020000
20220730_023000
20220730_030000
20220730_033000
20220730_040000
20220730_043000
20220730_050000
20220730_053000
20220730_060000
20220730_063000
20220730_070000
20220730_073000
20220730_080000
20220730_083000
20220730_090000
20220730_093000
20220730_100000
20220730_103000
20220730_110000
20220730_113000
20220730_120000
20220730_123000
20220730_130000
20220730_133000
20220730_140000
20220730_143000
20220730_150000
20220730_153000
20220731_000000
20220731_003000
20220731_010000
20220731_013000
20220731_020000
20220731_023000
20220731_030000
20220731_033000
20220731_040000
20220731_043000
20220731_050000
20220731_053000
20220731_060000
20220731_063000
20220731_070000
20220731_073000
20220731_080000
20220731_083000
20220731_090000
20220731_093000
20220731_100000
20220731_103000
20220731_110000
20220731_113000
20220731_120000
20220731_123000
20220731_130000
20220731_133000
20220731_140000
20220731_143000
20220731_150000
20220731_153000
20220801_000000
20220801_003000
20220801_010000
20220801_013000
20220801_020000
20220801_023000
20220801_030000
20220801_033000
20220801_040000
20220801_043000
20220801_050000
20220801_053000
20220801_060000
20220801_063000
20220801_070000
20220801_073000
20220801_080000
20220801_083000
20220801_090000
20220801_093000
20220801_100000
20220801_103000
20220801_110000
20220801_113000
20220801_120000
20220801_123000
20220801_130000
20220801_133000
20220801_140000
20220801_143000
20220801_150000
20220801_153000
20220802_000000
20220802_003000
20220802_010000
20220802_013000
20220802_020000
20220802_023000
20220802_030000
20220802_033000
20220802_040000
20220802_043000
20220802_050000
20220802_053000
20220802_060000
20220802_063000
20220802_070000
20220802_073000
20220802_080000
20220802_083000
20220802_090000
20220802_093000
20220802_100000
20220802_103000
20220802_110000
20220802_113000
20220802_120000
20220802_123000
20220802_130000
20220802_133000
20220802_140000
20220802_143000
20220802_150000
20220802_153000
20220803_000000
20220803_003000
20220803_010000
20220803_013000
20220803_020000
20220803_023000
20220803_030000
20220803_033000
20220803_040000
20220803_043000
20220803_050000
20220803_053000
20220803_060000
20220803_063000
20220803_070000
20220803_073000
20220803_080000
20220803_083000
20220803_090000
20220803_093000
20220803_100000
20220803_103000
20220803_110000
20220803_113000
20220803_120000
20220803_123000
20220803_130000
20220803_133000
20220803_140000
20220803_143000
20220803_150000
20220803_153000
20220804_000000
20220804_003000
20220804_010000
20220804_013000
20220804_020000
20220804_023000
20220804_030000
20220804_033000
20220804_040000
20220804_043000
20220804_050000
20220804_053000
20220804_060000
20220804_063000
20220804_070000
20220804_073000
20220804_080000
20220804_083000
20220804_090000
20220804_093000
20220804_100000
20220804_103000
20220804_110000
20220804_113000
20220804_120000
20220804_123000
20220804_130000
20220804_133000
20220804_140000
20220804_143000
20220804_150000
20220804_153000
20220805_000000
20220805_003000
20220805_010000
20220805_013000
20220805_020000
20220805_023000
20220805_030000
20220805_033000
20220805_040000
20220805_043000
20220805_050000
20220805_053000
20220805_060000
20220805_063000
20220805_070000
20220805_073000
20220805_080000
20220805_083000
20220805_090000
20220805_093000
20220805_100000
20220805_103000
20220805_110000
20220805_113000
20220805_120000
20220805_123000
20220805_130000
20220805_133000
20220805_140000
20220805_143000
20220805_150000
20220805_153000
20220806_000000
20220806_003000
20220806_010000
20220806_013000
20220806_020000
20220806_023000
20220806_030000
20220806_033000
20220806_040000
20220806_043000
20220806_050000
20220806_053000
20220806_060000
20220806_063000
20220806_070000
20220806_073000
20220806_080000
20220806_083000
20220806_090000
20220806_093000
20220806_100000
20220806_103000
20220806_110000
20220806_113000
20220806_120000
20220806_123000
20220806_130000
20220806_133000
20220806_140000
20220806_143000
20220806_150000
20220806_153000
20220807_000000
20220807_003000
20220807_010000
20220807_013000
20220807_020000
20220807_023000
20220807_030000
20220807_033000
20220807_040000
20220807_043000
20220807_050000
20220807_053000
20220807_060000
20220807_063000
20220807_070000
20220807_073000
20220807_080000
20220807_083000
20220807_090000
20220807_093000
20220807_100000
20220807_103000
20220807_110000
20220807_113000
20220807_120000
20220807_123000
20220807_130000
20220807_133000
20220807_140000
20220807_143000
20220807_150000
20220807_153000
20220808_000000
20220808_003000
20220808_010000
20220808_013000
20220808_020000
20220808_023000
20220808_030000
20220808_033000
20220808_040000
20220808_043000
20220808_050000
20220808_053000
20220808_060000
20220808_063000
20220808_070000
20220808_073000
20220808_080000
20220808_083000
20220808_090000
20220808_093000
20220808_100000
20220808_103000
20220808_110000
20220808_113000
20220808_120000
20220808_123000
20220808_130000
20220808_133000
20220808_140000
20220808_143000
20220808_150000
20220808_153000
20220809_000000
20220809_003000
20220809_010000
20220809_013000
20220809_020000
20220809_023000
20220809_030000
20220809_033000
20220809_040000
20220809_043000
20220809_050000
20220809_053000
20220809_060000
20220809_063000
20220809_070000
20220809_073000
20220809_080000
20220809_083000
20220809_090000
20220809_093000
20220809_100000
20220809_103000
20220809_110000
20220809_113000
20220809_120000
20220809_123000
20220809_130000
20220809_133000
20220809_140000
20220809_143000
20220809_150000
20220809_153000
20220810_000000
20220810_003000
20220810_010000
20220810_013000
20220810_020000
20220810_023000
20220810_030000
20220810_033000
20220810_040000
20220810_043000
20220810_050000
20220810_053000
20220810_060000
20220810_063000
20220810_070000
20220810_073000
20220810_080000
20220810_083000
20220810_090000
20220810_093000
20220810_100000
20220810_103000
20220810_110000
20220810_113000
20220810_120000
20220810_123000
20220810_130000
20220810_133000
20220810_140000
20220810_143000
20220810_150000
20220810_153000
20220811_000000
20220811_003000
20220811_010000
20220811_013000
20220811_020000
20220811_023000
20220811_030000
20220811_033000
20220811_040000
20220811_043000
20220811_050000
20220811_053000
20220811_060000
20220811_063000
20220811_070000
20220811_073000
20220811_080000
20220811_083000
20220811_090000
20220811_093000
20220811_100000
20220811_103000
20220811_110000
20220811_113000
20220811_120000
20220811_123000
20220811_130000
20220811_133000
20220811_140000
20220811_143000
20220811_150000
20220811_153000
20220812_000000
20220812_003000
20220812_010000
20220812_013000
20220812_020000
20220812_023000
20220812_030000
20220812_033000
20220812_040000
20220812_043000
20220812_050000
20220812_053000
20220812_060000
20220812_063000
20220812_070000
20220812_073000
20220812_080000
20220812_083000
20220812_090000
20220812_093000
20220812_100000
20220812_103000
20220812_110000
20220812_113000
20220812_120000
20220812_123000
20220812_130000
20220812_133000
20220812_140000
20220812_143000
20220812_150000
20220812_153000
20220813_000000
20220813_003000
20220813_010000
20220813_013000
20220813_020000
20220813_023000
20220813_030000
20220813_033000
20220813_040000
20220813_043000
20220813_050000
20220813_053000
20220813_060000
20220813_063000
20220813_070000
20220813_073000
20220813_080000
20220813_083000
20220813_090000
20220813_093000
20220813_100000
20220813_103000
20220813_110000
20220813_113000
20220813_120000
20220813_123000
20220813_130000
20220813_133000
20220813_140000
20220813_143000
20220813_150000
20220813_153000
20220814_000000
20220814_003000
20220814_010000
20220814_013000
20220814_020000
20220814_023000
20220814_030000
20220814_033000
20220814_040000
20220814_043000
20220814_050000
20220814_053000
20220814_060000
20220814_063000
20220814_070000
20220814_073000
20220814_080000
20220814_083000
20220814_090000
20220814_093000
20220814_100000
20220814_103000
20220814_110000
20220814_113000
20220814_120000
20220814_123000
20220814_130000
20220814_133000
20220814_140000
20220814_143000
20220814_150000
20220814_153000
20220815_000000
20220815_003000
20220815_010000
20220815_013000
20220815_020000
20220815_023000
20220815_030000
20220815_033000
20220815_040000
20220815_043000
20220815_050000
20220815_053000
20220815_060000
20220815_063000
20220815_070000
20220815_073000
20220815_080000
20220815_083000
20220815_090000
20220815_093000
20220815_100000
20220815_103000
20220815_110000
20220815_113000
20220815_120000
20220815_123000
20220815_130000
20220815_133000
20220815_140000
20220815_143000
20220815_150000
20220815_153000
20220816_000000
20220816_003000
20220816_010000
20220816_013000
20220816_020000
20220816_023000
20220816_030000
20220816_033000
20220816_040000
20220816_043000
20220816_050000
20220816_053000
20220816_060000
20220816_063000
20220816_070000
20220816_073000
20220816_080000
20220816_083000
20220816_090000
20220816_093000
20220816_100000
20220816_103000
20220816_110000
20220816_113000
20220816_120000
20220816_123000
20220816_130000
20220816_133000
20220816_140000
20220816_143000
20220816_150000
20220816_153000
20220817_000000
20220817_003000
20220817_010000
20220817_013000
20220817_020000
20220817_023000
20220817_030000
20220817_033000
20220817_040000
20220817_043000
20220817_050000
20220817_053000
20220817_060000
20220817_063000
20220817_070000
20220817_073000
20220817_080000
20220817_083000
20220817_090000
20220817_093000
20220817_100000
20220817_103000
20220817_110000
20220817_113000
20220817_120000
20220817_123000
20220817_130000
20220817_133000
20220817_140000
20220817_143000
20220817_150000
20220817_153000
20220818_000000
20220818_003000
20220818_010000
20220818_013000
20220818_020000
20220818_023000
20220818_030000
20220818_033000
20220818_040000
20220818_043000
20220818_050000
20220818_053000
20220818_060000
20220818_063000
20220818_070000
20220818_073000
20220818_080000
20220818_083000
20220818_090000
20220818_093000
20220818_100000
20220818_103000
20220818_110000
20220818_113000
20220818_120000
20220818_123000
20220818_130000
20220818_133000
20220818_140000
20220818_143000
20220818_150000
20220818_153000
20220819_000000
20220819_003000
20220819_020000
20220819_023000
20220819_030000
20220819_033000
20220819_040000
20220819_043000
20220819_050000
20220819_053000
20220819_060000
20220819_063000
20220819_070000
20220819_073000
20220819_080000
20220819_083000
20220819_090000
20220819_093000
20220819_100000
20220819_103000
20220819_110000
20220819_113000
20220819_120000
20220819_123000
20220819_130000
20220819_133000
20220819_140000
20220819_143000
20220819_150000
20220819_153000
20220820_000000
20220820_003000
20220820_010000
20220820_013000
20220820_020000
20220820_023000
20220820_030000
20220820_033000
20220820_040000
20220820_043000
20220820_050000
20220820_053000
20220820_060000
20220820_063000
20220820_070000
20220820_073000
20220820_080000
20220820_083000
20220820_090000
20220820_093000
20220820_100000
20220820_103000
20220820_110000
20220820_113000
20220820_120000
20220820_123000
20220820_130000
20220820_133000
20220820_140000
20220820_143000
20220820_150000
20220820_153000
20220821_000000
20220821_003000
20220821_010000
20220821_013000
20220821_020000
20220821_023000
20220821_030000
20220821_033000
20220821_040000
20220821_043000
20220821_050000
20220821_053000
20220821_060000
20220821_063000

Empty DataFrame
Columns: []
Index: []

In [24]:
def save_individual_file_raw_dets(file_dets):
    print(f'{Path(file_dets.name).stem}')
    save_filename = f'{data_params["detector_tag"]}__{data_params["site_tag"]}_{Path(file_dets.name).stem}'
    save_dets = file_dets[file_dets['det_prob']>=0.2].copy()
    save_dets.to_csv(f'/Users/adityakrishna/duty-cycle-analysis/data/raw/{data_params["site_tag"]}/{save_filename}.csv')

In [25]:
raw_files = sorted(list(Path(file_paths['raw_SITE_folder']).glob(f'{data_params["detector_tag"]}__{data_params["site_tag"]}*.csv')))
for raw_filepath in raw_files:
    file_dets = pd.read_csv(raw_filepath)
    save_dets = file_dets[file_dets['det_prob']>=0.2].copy()
    save_dets.to_csv(f'/Users/adityakrishna/duty-cycle-analysis/data/raw/{data_params["site_tag"]}/{raw_filepath.name}')